version: '3'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ead-authuser
    ports:
      - "5433:5432"
    volumes:
      - authuser-data:/var/lib/postgresql/data
    networks:
      - authuser-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - authuser-network

volumes:
  authuser-data:

networks:
  authuser-network:
    driver: bridge